### ISSUE TITLE
Use UnoCSS directive transformers

### ISSUE THREAD

**Issue by emi420** [hotosm/ui#51]
Instead of adding classes to the element:

```html
<h1 class="hot-text-2xl hot-color-primary hot-font-sans hot-font-bold hot-pl-3 hot-m-0">
```

Use `@apply` (or `--at-apply`)

```css
.hot-header-h1 {
  @apply: hot-text-2xl hot-color-primary hot-font-sans hot-font-bold hot-pl-3 hot-m-0;
}
```

And then the single class:

```html
<h1 class="hot-header-h1">
```
